version: '3.8'

services:
  node_exporter:
    image: hatamiarash7/netflow-exporter:v1.0.0
    pid: host
    restart: unless-stopped
    ports:
      - "2055:2055/udp"
      - "9438:9438"
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana-oss
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
